# -*- coding: utf-8 -*-
"""loan_fin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ApUftH9s0D0FevJitYmS9ZBr99J-Dl3d
"""

import pandas as pd

df = pd.read_csv("loan.csv")

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Convert target to binary
df['loan_status'] = df['loan_status'].map({
    'Approved': 1,
    'Rejected': 0
})

# Convert categorical columns
df = pd.get_dummies(df, drop_first=True)

df.head()

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

import pickle

# Load dataset
df = pd.read_csv("loan.csv")

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Check first rows
df.head()

# Load dataset again to ensure 'loan_status' is string type
df = pd.read_csv("loan.csv")

# Remove extra spaces from column names (as done in other cells)
df.columns = df.columns.str.strip()

# Convert loan_status to binary
df['loan_status'] = df['loan_status'].str.strip().map({
    'Approved': 1,
    'Rejected': 0
})

df['loan_status'].value_counts()

# Convert categorical columns into numeric
df = pd.get_dummies(df, drop_first=True)

df.head()

X = df.drop("loan_status", axis=1)
y = df["loan_status"]

X.shape, y.shape

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

valid_indices = y_train.dropna().index


X_train_cleaned = X_train.loc[valid_indices]
y_train_cleaned = y_train.loc[valid_indices]

model = LogisticRegression(max_iter=1000)
model.fit(X_train_cleaned, y_train_cleaned)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

importance = model.coef_[0]
features = X.columns

explain_df = pd.DataFrame({
    "Feature": features,
    "Impact": importance
}).sort_values(by="Impact", ascending=False)

explain_df.head(10)

pickle.dump(model, open("loan_model.pkl", "wb"))